FROM python:3.12-slim

WORKDIR /app

RUN pip install uv

COPY pyproject.toml uv.lock ./

RUN uv sync --frozen

COPY . .

EXPOSE 7860

CMD ["uv", "run", "streamlit", "run", "main.py", "--server.port=7860", "--server.address=0.0.0.0"]
